import "./globals.css";
import { Inter, Urbanist } from "next/font/google";
import { ReduxProvider } from "@/redux/provider";

const interFont = Inter({ subsets: ["latin"], weight: ["400", "600", "900"] });
const urbanistFont = Urbanist({ subsets: ["latin"], weight: ["400", "600", "900"] });

export const metadata = {
  title: "Perritos Callejeros 2016",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id="RootLayout" className={urbanistFont.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}