"use client"
import { Provider } from "react-redux";
import "./globals.css";
import { Inter, Roboto_Mono } from "next/font/google";
import { store } from "@/redux/store";

const inter = Inter({ subsets: ["latin"], weight: ["400", "600", "900"] });
const roboto = Inter({ subsets: ["latin"], weight: ["400", "600", "900"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={roboto.className}>{children}</body>
      </html>
    </Provider>
  );
}
